---
name: Solicitud de funcionalidad
about: Sugiere una idea para mejorar SaraIA
title: '[FEATURE] '
labels: enhancement
assignees: ''
---

**¿Tu solicitud está relacionada con un problema? Descríbelo**
Una descripción clara y concisa del problema. Ej: Siempre me frustra cuando [...]

**Describe la solución que te gustaría**
Una descripción clara y concisa de lo que quieres que ocurra.

**Alternativas consideradas**
Una descripción de cualquier solución o funcionalidad alternativa que hayas considerado.

**Contexto adicional**
Cualquier otro contexto o capturas de pantalla sobre la solicitud.
